---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 719440797972561920-q7NszfzbeO15IZm3vTIGOqaFpQEOCau
:access_token_secret: zya2nDT4C12DonQll445Y3eIAPhivKOToe92UoaR3uhWk
